### ISSUE TITLE
Home page, list regions as dropdown instead of a container for each?

### ISSUE THREAD

**Issue by RyanTG** [RyanTG/pbm#119]
The home page currently lists every region, with # of locations/machines for each. Is this TMI / intimidating for first time visitors? Would a simple dropdown listing all the regions be better?

The home page would then just have:
1) the description container
2) the twitter feed
3) the map
4) dropdown of regions

@scottwainstock any thoughts?

**Comment by scottwainstock** [comment]
@RyanTG It'd be nice to keep the every region view in SOME way... like make it show up if you click a button or something?

It seems like the best thing would be to have the region closest to the viewer show up at the top, and then have all the other regions below it. But, that might get annoying because it forces people to answer that "do you want to share your location" question.

I just don't know.

**Comment by RyanTG** [comment]
Another home page idea: use geolocation to load nearby locations (say, four random ones). This only really works if the homepage also redirects you to your closest region.

**Comment by RyanTG** [comment]
For inspiration, look at some home delivery sites, like https://postmates.com/
They all have an "enter your location" input box, then a list of regions below (and the list is simpler than ours - just a name)
